//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public Historial()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Creado { get; set; }
        public int Estado { get; set; }
        public double Total { get; set; }
        public double Deuda { get; set; }
        public string Patente { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
