//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Producto> ProductoSet { get; set; }
        public DbSet<Categoria> CategoriaSet { get; set; }
        public DbSet<Historial> HistorialSet { get; set; }
        public DbSet<Cliente> ClienteSet { get; set; }
        public DbSet<Permiso> PermisoSet { get; set; }
        public DbSet<Rol> RolSet { get; set; }
        public DbSet<Usuario> UsuarioSet { get; set; }
    }
}
