//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public Permiso()
        {
            this.Rol = new HashSet<Rol>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Rol> Rol { get; set; }
    }
}
