//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Historial = new HashSet<Historial>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public double Precio { get; set; }
        public string Marca { get; set; }
        public int Estado { get; set; }
        public string StockMinimo { get; set; }
        public System.DateTime Creado { get; set; }
        public string Descripcion { get; set; }
        public int Stock { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Historial> Historial { get; set; }
    }
}
